volume_balok = ('Volume Balok Adalah : ')
p = int(input('masukan panjang balok : '))
l = int(input('masukan lebar balok : '))
t = int(input('masukan tinggi balok : '))
volume = (p*l*t)
print(volume_balok,volume)
